package org.earthChem.db.postgresql.hbm;

// Generated Jul 30, 2014 4:07:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.earthChem.presentation.jsf.theme.Theme;

/**
 * Affiliation generated by hbm2java
 */

public class Affiliation implements java.io.Serializable {

	private int affiliationNum;
	private Organization organization;
	private Person person;
	private Boolean isPrimaryOrganizationContact;
	private Date affiliationStartDate;
	private Date affiliationEndDate;
	private String primaryPhone;
	private String primaryEmail;
	private String primaryAddress;
	private String personLink;
	private Set actionBies = new HashSet(0);

	private int personNum;
	private Integer organizationNum;
	private String organizationName;
	private String fax;
	private String title;
	private Theme selectedOrg;
	
	
	public Affiliation() {
	}

	public Affiliation(int affiliationNum, Organization organization,
			Person person) {
		this.affiliationNum = affiliationNum;
		this.organization = organization;
		this.person = person;
	}

	public Affiliation(int affiliationNum, Organization organization,
			Person person,String primaryPhone, String primaryEmail) {
		this.affiliationNum = affiliationNum;
		this.organization = organization;
		this.person = person;
		this.primaryPhone = primaryPhone;
		this.primaryEmail = primaryEmail;
	}
	
	public Affiliation(int affiliationNum, Organization organization,
			Person person, Boolean isPrimaryOrganizationContact,
			Date affiliationStartDate, Date affiliationEndDate,
			String primaryPhone, String primaryEmail, String primaryAddress,
			String personLink, Set actionBies) {
		this.affiliationNum = affiliationNum;
		this.organization = organization;
		this.person = person;
		this.isPrimaryOrganizationContact = isPrimaryOrganizationContact;
		this.affiliationStartDate = affiliationStartDate;
		this.affiliationEndDate = affiliationEndDate;
		this.primaryPhone = primaryPhone;
		this.primaryEmail = primaryEmail;
		this.primaryAddress = primaryAddress;
		this.personLink = personLink;
		this.actionBies = actionBies;
	}

	
	public int getAffiliationNum() {
		return this.affiliationNum;
	}

	public void setAffiliationNum(int affiliationNum) {
		this.affiliationNum = affiliationNum;
	}


	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	
	public Boolean getIsPrimaryOrganizationContact() {
		return this.isPrimaryOrganizationContact;
	}

	public void setIsPrimaryOrganizationContact(
			Boolean isPrimaryOrganizationContact) {
		this.isPrimaryOrganizationContact = isPrimaryOrganizationContact;
	}

	
	public Date getAffiliationStartDate() {
		return this.affiliationStartDate;
	}

	public void setAffiliationStartDate(Date affiliationStartDate) {
		this.affiliationStartDate = affiliationStartDate;
	}

	
	public Date getAffiliationEndDate() {
		return this.affiliationEndDate;
	}

	public void setAffiliationEndDate(Date affiliationEndDate) {
		this.affiliationEndDate = affiliationEndDate;
	}

	
	public String getPrimaryPhone() {
		return this.primaryPhone;
	}

	public void setPrimaryPhone(String primaryPhone) {
		this.primaryPhone = primaryPhone;
	}

	
	public String getPrimaryEmail() {
		return this.primaryEmail;
	}

	public void setPrimaryEmail(String primaryEmail) {
		this.primaryEmail = primaryEmail;
	}

	
	public String getPrimaryAddress() {
		return this.primaryAddress;
	}

	public void setPrimaryAddress(String primaryAddress) {
		this.primaryAddress = primaryAddress;
	}

	
	public String getPersonLink() {
		return this.personLink;
	}

	public void setPersonLink(String personLink) {
		this.personLink = personLink;
	}

	
	public Set getActionBies() {
		return this.actionBies;
	}

	public void setActionBies(Set actionBies) {
		this.actionBies = actionBies;
	}

	public int getPersonNum() {
		return personNum;
	}

	public void setPersonNum(int personNum) {
		this.personNum = personNum;
	}

	public Integer getOrganizationNum() {
		return organizationNum;
	}

	public void setOrganizationNum(Integer organizationNum) {
		this.organizationNum = organizationNum;
	}

	public String getOrganizationName() {
		return organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Theme getSelectedOrg() {
		return selectedOrg;
	}

	public void setSelectedOrg(Theme selectedOrg) {
		this.selectedOrg = selectedOrg;
	}

	
}
