package org.earthChem.db.postgresql.hbm;

// Generated Jul 30, 2014 4:07:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;


/**
 * Method generated by hbm2java
 */

public class Annotation implements java.io.Serializable {

	public static Integer AlterationType=12;
	public static Integer Rocktexture=16;
	public static Integer SampleComment=22;
	public static Integer RockclassDetail=15;
	public static Integer Alias=11;
	public static Integer Alteration=13;
	public static Integer GeologicAge=26;
	
	private Integer annotationNum;
	private Integer sfAnnotationNum;
	private Integer annotationTypeNum;
	private Integer dataSourceNum;
	private String annotationText;
	private String annotationName;
	private String annotationTypeName;
	
	public Integer getSfAnnotationNum() {
		return sfAnnotationNum;
	}
	public void setSfAnnotationNum(Integer sfAnnotationNum) {
		this.sfAnnotationNum = sfAnnotationNum;
	}
	public Integer getAnnotationNum() {
		return annotationNum;
	}
	public void setAnnotationNum(Integer annotationNum) {
		this.annotationNum = annotationNum;
	}
	public Integer getAnnotationTypeNum() {
		return annotationTypeNum;
	}
	public void setAnnotationTypeNum(Integer annotationTypeNum) {
		this.annotationTypeNum = annotationTypeNum;
	}
	public Integer getDataSourceNum() {
		return dataSourceNum;
	}
	public void setDataSourceNum(Integer dataSourceNum) {
		this.dataSourceNum = dataSourceNum;
	}
	public String getAnnotationText() {
		return annotationText;
	}
	public void setAnnotationText(String annotationText) {
		this.annotationText = annotationText;
	}
	public String getAnnotationName() {
		return annotationName;
	}
	public void setAnnotationName(String annotationName) {
		this.annotationName = annotationName;
	}
	public String getAnnotationTypeName() {
		return annotationTypeName;
	}
	public void setAnnotationTypeName(String annotationTypeName) {
		this.annotationTypeName = annotationTypeName;
	}
	

	
}
