package org.earthChem.db.postgresql.hbm;

// Generated Jul 30, 2014 4:07:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;


/**
 * Citation generated by hbm2java
 */

public class Citation implements java.io.Serializable {

	private Integer citationNum;
	private String title;
	private String publisher;
//	private int publicationYear;
	private Integer publicationYear;
	private String citationLink;
	private String journal;
	private String issue;
	private String volume;
	private Integer firstPage;
	private Integer lastPage;
	private String bookTitle;
	private String bookEditor;
	private String citationAbstract;
	private Set samplingFeatureAnnotations = new HashSet(0);
	private Set referenceMaterialValues = new HashSet(0);
	private Set featureOfInterestAnnotations = new HashSet(0);
	private Set authorLists = new HashSet(0);
	private Set citationDatasets = new HashSet(0);
	private Set resultAnnotations = new HashSet(0);
	private Set citationExternalIdentifiers = new HashSet(0);
	private Set ecStatusInfos = new HashSet(0);
	private String doi;
	private String dataStatus="IN_QUEUE";
	private String publicComment;
	private String internalComment;
	private String authors;
	private String doiAuthors;
	private String viewAuthors;
	private String pages;
	private String errorMsg;

	public Citation() {
	}
	
	
	public String getErrorMsg() {
		return errorMsg;
	}


	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}


	public Citation(Integer citationNum) {
		this.citationNum = citationNum;
	}

	public Citation(Integer citationNum, String title, String publisher,
			int publicationYear, String citationLink) {
		this.citationNum = citationNum;
		this.title = title;
		this.publisher = publisher;
		this.publicationYear = publicationYear;
		this.citationLink = citationLink;
	}

	public Citation(Integer citationNum, String title, String publisher,
			int publicationYear, String citationLink, String journal,
			String issue, String volume, Integer firstPage, Integer lastPage,
			String bookTitle, String bookEditor, String citationAbstract,
			Set samplingFeatureAnnotations, Set referenceMaterialValues,
			Set featureOfInterestAnnotations, Set authorLists,
			Set citationDatasets, Set resultAnnotations,
			Set citationExternalIdentifiers, Set ecStatusInfos) {
		this.citationNum = citationNum;
		this.title = title;
		this.publisher = publisher;
		this.publicationYear = publicationYear;
		this.citationLink = citationLink;
		this.journal = journal;
		this.issue = issue;
		this.volume = volume;
		this.firstPage = firstPage;
		this.lastPage = lastPage;
		this.bookTitle = bookTitle;
		this.bookEditor = bookEditor;
		this.citationAbstract = citationAbstract;
		this.samplingFeatureAnnotations = samplingFeatureAnnotations;
		this.referenceMaterialValues = referenceMaterialValues;
		this.featureOfInterestAnnotations = featureOfInterestAnnotations;
		this.authorLists = authorLists;
		this.citationDatasets = citationDatasets;
		this.resultAnnotations = resultAnnotations;
		this.citationExternalIdentifiers = citationExternalIdentifiers;
		this.ecStatusInfos = ecStatusInfos;
	}

	public Integer getCitationNum() {
		return this.citationNum;
	}

	public void setCitationNum(Integer citationNum) {
		this.citationNum = citationNum;
	}
	
	
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Integer getPublicationYear() {
		return this.publicationYear;
	}

	public void setPublicationYear(Integer publicationYear) {
		this.publicationYear = publicationYear;
	}

	public String getCitationLink() {
		return this.citationLink;
	}

	public void setCitationLink(String citationLink) {
		this.citationLink = citationLink;
	}

	public String getJournal() {
		return this.journal;
	}

	public void setJournal(String journal) {
		this.journal = journal;
	}

	public String getIssue() {
		return this.issue;
	}

	public void setIssue(String issue) {
		this.issue = issue;
	}

	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	public Integer getFirstPage() {
		return this.firstPage;
	}

	public void setFirstPage(Integer firstPage) {
		this.firstPage = firstPage;
	}

	public Integer getLastPage() {
		return this.lastPage;
	}

	public void setLastPage(Integer lastPage) {
		this.lastPage = lastPage;
	}

	public String getBookTitle() {
		return this.bookTitle;
	}

	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

	public String getBookEditor() {
		return this.bookEditor;
	}

	public void setBookEditor(String bookEditor) {
		this.bookEditor = bookEditor;
	}

	public String getCitationAbstract() {
		return this.citationAbstract;
	}

	public void setCitationAbstract(String citationAbstract) {
		this.citationAbstract = citationAbstract;
	}

	public Set getSamplingFeatureAnnotations() {
		return this.samplingFeatureAnnotations;
	}

	public void setSamplingFeatureAnnotations(Set samplingFeatureAnnotations) {
		this.samplingFeatureAnnotations = samplingFeatureAnnotations;
	}

	public Set getReferenceMaterialValues() {
		return this.referenceMaterialValues;
	}

	public void setReferenceMaterialValues(Set referenceMaterialValues) {
		this.referenceMaterialValues = referenceMaterialValues;
	}

	public Set getFeatureOfInterestAnnotations() {
		return this.featureOfInterestAnnotations;
	}

	public void setFeatureOfInterestAnnotations(Set featureOfInterestAnnotations) {
		this.featureOfInterestAnnotations = featureOfInterestAnnotations;
	}

	public Set getAuthorLists() {
		return this.authorLists;
	}

	public void setAuthorLists(Set authorLists) {
		this.authorLists = authorLists;
	}

	public Set getCitationDatasets() {
		return this.citationDatasets;
	}

	public void setCitationDatasets(Set citationDatasets) {
		this.citationDatasets = citationDatasets;
	}

	public Set getResultAnnotations() {
		return this.resultAnnotations;
	}

	public void setResultAnnotations(Set resultAnnotations) {
		this.resultAnnotations = resultAnnotations;
	}

	public Set getCitationExternalIdentifiers() {
		return this.citationExternalIdentifiers;
	}

	public void setCitationExternalIdentifiers(Set citationExternalIdentifiers) {
		this.citationExternalIdentifiers = citationExternalIdentifiers;
	}

	public Set getEcStatusInfos() {
		return this.ecStatusInfos;
	}

	public void setEcStatusInfos(Set ecStatusInfos) {
		this.ecStatusInfos = ecStatusInfos;
	}

	public String getDoi() {
		return doi;
	}

	public void setDoi(String doi) {
		this.doi = doi;
	}

	public String getDataStatus() {
		return dataStatus;
	}

	public void setDataStatus(String dataStatus) {
		this.dataStatus = dataStatus;
	}

	public String getPublicComment() {
		return publicComment;
	}

	public void setPublicComment(String publicComment) {
		this.publicComment = publicComment;
	}

	public String getInternalComment() {
		return internalComment;
	}

	public void setInternalComment(String internalComment) {
		this.internalComment = internalComment;
	}

	public String getAuthors() {
		return authors;
	}

	public void setAuthors(String authors) {
		this.authors = authors;
	}

	public String getDoiAuthors() {
		return doiAuthors;
	}

	public void setDoiAuthors(String doiAuthors) {
		this.doiAuthors = doiAuthors;
	}

	public String getViewAuthors() {
		return viewAuthors;
	}

	public void setViewAuthors(String viewAuthors) {
		this.viewAuthors = viewAuthors;
	}

	public String getPages() {
		return pages;
	}

	public void setPages(String pages) {
		this.pages = pages;
	}

	
	
}
