package org.earthChem.db.postgresql.hbm;

// Generated Jul 30, 2014 4:07:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;


/**
 * Method generated by hbm2java
 */

public class Method implements java.io.Serializable {

	private Integer methodNum;
	private Integer methodTypeNum;
	private Integer organizationNum;
	private String organizationName;
	private String methodCode;
	private String methodName;
	private String methodTypeName;
	private String methodDescription;
	private String methodLink;
	private Organization organization;
	
	
	
	public String getOrganizationName() {
		return organizationName;
	}
	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}
	public Organization getOrganization() {
		return organization;
	}
	public void setOrganization(Organization organization) {
		this.organization = organization;
	}
	public String getMethodTypeName() {
		return methodTypeName;
	}
	public void setMethodTypeName(String methodTypeName) {
		this.methodTypeName = methodTypeName;
	}
	public Integer getMethodNum() {
		return methodNum;
	}
	public void setMethodNum(Integer methodNum) {
		this.methodNum = methodNum;
	}
	public Integer getMethodTypeNum() {
		return methodTypeNum;
	}
	public void setMethodTypeNum(Integer methodTypeNum) {
		this.methodTypeNum = methodTypeNum;
	}
	public Integer getOrganizationNum() {
		return organizationNum;
	}
	public void setOrganizationNum(Integer organizationNum) {
		this.organizationNum = organizationNum;
	}
	public String getMethodCode() {
		return methodCode;
	}
	public void setMethodCode(String methodCode) {
		this.methodCode = methodCode;
	}
	public String getMethodName() {
		return methodName;
	}
	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}
	public String getMethodDescription() {
		return methodDescription;
	}
	public void setMethodDescription(String methodDescription) {
		this.methodDescription = methodDescription;
	}
	public String getMethodLink() {
		return methodLink;
	}
	public void setMethodLink(String methodLink) {
		this.methodLink = methodLink;
	}

	
	
	
	
	

	
}
