package org.earthChem.db.postgresql.hbm;

// Generated Jul 30, 2014 4:07:06 PM by Hibernate Tools 4.0.0

/**
 * PersonExternalIdentifier generated by hbm2java
 */

public class PersonExternalIdentifier implements java.io.Serializable {

	private int bridgeNum;
	private Person person;
//	private ExternalIdentifierSystem externalIdentifierSystem;
	private String personExternalIdentifier;
	private String personExternalIdentifierUri;
	private Integer externalIdentifierSystemNum = 1; //ORCID
	private String externalIdentifierSystemName;
	
	public PersonExternalIdentifier() {
	}
/*
	public PersonExternalIdentifier(int bridgeNum, Person person,
			ExternalIdentifierSystem externalIdentifierSystem,
			String personExternalIdentifier) {
		this.bridgeNum = bridgeNum;
		this.person = person;
		this.externalIdentifierSystem = externalIdentifierSystem;
		this.personExternalIdentifier = personExternalIdentifier;
	}

	public PersonExternalIdentifier(int bridgeNum, Person person,
			ExternalIdentifierSystem externalIdentifierSystem,
			String personExternalIdentifier, String personExternalIdentifierUri) {
		this.bridgeNum = bridgeNum;
		this.person = person;
		this.externalIdentifierSystem = externalIdentifierSystem;
		this.personExternalIdentifier = personExternalIdentifier;
		this.personExternalIdentifierUri = personExternalIdentifierUri;
	}
*/
	
	public int getBridgeNum() {
		return this.bridgeNum;
	}

	public void setBridgeNum(int bridgeNum) {
		this.bridgeNum = bridgeNum;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

/*
	public ExternalIdentifierSystem getExternalIdentifierSystem() {
		return this.externalIdentifierSystem;
	}

	public void setExternalIdentifierSystem(
			ExternalIdentifierSystem externalIdentifierSystem) {
		this.externalIdentifierSystem = externalIdentifierSystem;
	}
*/
	
	public String getPersonExternalIdentifier() {
		return this.personExternalIdentifier;
	}

	public void setPersonExternalIdentifier(String personExternalIdentifier) {
		this.personExternalIdentifier = personExternalIdentifier;
	}


	public String getPersonExternalIdentifierUri() {
		return this.personExternalIdentifierUri;
	}

	public void setPersonExternalIdentifierUri(
			String personExternalIdentifierUri) {
		this.personExternalIdentifierUri = personExternalIdentifierUri;
	}

	public Integer getExternalIdentifierSystemNum() {
		return externalIdentifierSystemNum;
	}

	public void setExternalIdentifierSystemNum(Integer externalIdentifierSystemNum) {
		this.externalIdentifierSystemNum = externalIdentifierSystemNum;
	}

	public String getExternalIdentifierSystemName() {
		return externalIdentifierSystemName;
	}

	public void setExternalIdentifierSystemName(String externalIdentifierSystemName) {
		this.externalIdentifierSystemName = externalIdentifierSystemName;
	}

	
}
