package org.earthChem.db.postgresql.hbm;

// Generated Jul 30, 2014 4:07:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.List;
import java.util.Set;


/**
 * Method generated by hbm2java
 */

public class Station implements java.io.Serializable {
	
	private Integer samplingFeatureNum;
	private Integer samplingFeatureTypeNum;
	private Integer tectonicSettingNum;
	private String samplingFeatureCode;
	private String samplingFeatureName;
	private String geometry;
	private String samplingFeatureDescription;
	private String samplingFeatureGeotype="POINT";
	private String samplingFeatureTypeName;
	private Double elevationMin;
	private Double elevationMax;
	private Double lat1;
	private Double long1;
	private Double lat2;
	private Double long2;
	private String tectonicSettingName;
	private List<FeatureOfInterest> foiList;
	private List<Annotation> tsList; //tectonicSetting
//	private Integer dataSourceNum=0;
	
	
	
	
	
	public List<Annotation> getTsList() {
		return tsList;
	}
	public void setTsList(List<Annotation> tsList) {
		this.tsList = tsList;
	}

	public List<FeatureOfInterest> getFoiList() {
		return foiList;
	}
	public void setFoiList(List<FeatureOfInterest> foiList) {
		this.foiList = foiList;
	}
	public Integer getTectonicSettingNum() {
		return tectonicSettingNum;
	}
	public void setTectonicSettingNum(Integer tectonicSettingNum) {
		this.tectonicSettingNum = tectonicSettingNum;
	}
	public String getTectonicSettingName() {
		return tectonicSettingName;
	}
	public void setTectonicSettingName(String tectonicSettingName) {
		this.tectonicSettingName = tectonicSettingName;
	}
	public Double getLat2() {
		return lat2;
	}
	public void setLat2(Double lat2) {
		this.lat2 = lat2;
	}
	public Double getLong2() {
		return long2;
	}
	public void setLong2(Double long2) {
		this.long2 = long2;
	}
	public Double getLat1() {
		return lat1;
	}
	public void setLat1(Double lat1) {
		this.lat1 = lat1;
	}
	public Double getLong1() {
		return long1;
	}
	public void setLong1(Double long1) {
		this.long1 = long1;
	}
	public Integer getSamplingFeatureNum() {
		return samplingFeatureNum;
	}
	public void setSamplingFeatureNum(Integer samplingFeatureNum) {
		this.samplingFeatureNum = samplingFeatureNum;
	}
	public Integer getSamplingFeatureTypeNum() {
		return samplingFeatureTypeNum;
	}
	public void setSamplingFeatureTypeNum(Integer samplingFeatureTypeNum) {
		this.samplingFeatureTypeNum = samplingFeatureTypeNum;
	}
	public String getSamplingFeatureCode() {
		if(samplingFeatureCode != null) samplingFeatureCode= samplingFeatureCode.toUpperCase();
		return samplingFeatureCode;
	}
	public void setSamplingFeatureCode(String samplingFeatureCode) {
		if(samplingFeatureCode != null) samplingFeatureCode= samplingFeatureCode.toUpperCase();
		this.samplingFeatureCode = samplingFeatureCode;
	}
	public String getSamplingFeatureName() {
		return samplingFeatureName;
	}
	public void setSamplingFeatureName(String samplingFeatureName) {
		this.samplingFeatureName = samplingFeatureName;
	}
	public String getGeometry() {
		return geometry;
	}
	public void setGeometry(String geometry) {
		this.geometry = geometry;
	}
	public String getSamplingFeatureDescription() {
		return samplingFeatureDescription;
	}
	public void setSamplingFeatureDescription(String samplingFeatureDescription) {
		this.samplingFeatureDescription = samplingFeatureDescription;
	}
	public String getSamplingFeatureGeotype() {
		return samplingFeatureGeotype;
	}
	public void setSamplingFeatureGeotype(String samplingFeatureGeotype) {
		this.samplingFeatureGeotype = samplingFeatureGeotype;
	}
	public String getSamplingFeatureTypeName() {
		return samplingFeatureTypeName;
	}
	public void setSamplingFeatureTypeName(String samplingFeatureTypeName) {
		this.samplingFeatureTypeName = samplingFeatureTypeName;
	}
	public Double getElevationMin() {
		return elevationMin;
	}
	public void setElevationMin(Double elevationMin) {
		this.elevationMin = elevationMin;
	}
	public Double getElevationMax() {
		return elevationMax;
	}
	public void setElevationMax(Double elevationMax) {
		this.elevationMax = elevationMax;
	}
	
	
	
	
}
