package org.earthChem.db.postgresql.hbm;

// Generated Jul 30, 2014 4:07:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import org.earthChem.presentation.jsf.theme.Theme;


/**
 * Method generated by hbm2java
 */

public class Taxonomic implements java.io.Serializable {


	private Integer taxonomicClassifierNum;
	private Integer parentTaxonomicClassifierNum;
	private String taxonomicClassifierTypeCv;
	private String taxonomicClassifierName;
	private String parentTaxonomicClassifierName;
	private String taxonomicClassifierCommonName;
	private String taxonomicClassifierDescription;
	private Theme rockclassTheme;
	
	
	
	public Theme getRockclassTheme() {
		return rockclassTheme;
	}
	public void setRockclassTheme(Theme rockclassTheme) {
		this.rockclassTheme = rockclassTheme;
	}
	public String getParentTaxonomicClassifierName() {
		return parentTaxonomicClassifierName;
	}
	public void setParentTaxonomicClassifierName(String parentTaxonomicClassifierName) {
		this.parentTaxonomicClassifierName = parentTaxonomicClassifierName;
	}
	public Integer getTaxonomicClassifierNum() {
		return taxonomicClassifierNum;
	}
	public void setTaxonomicClassifierNum(Integer taxonomicClassifierNum) {
		this.taxonomicClassifierNum = taxonomicClassifierNum;
	}
	public Integer getParentTaxonomicClassifierNum() {
		return parentTaxonomicClassifierNum;
	}
	public void setParentTaxonomicClassifierNum(Integer parentTaxonomicClassifierNum) {
		this.parentTaxonomicClassifierNum = parentTaxonomicClassifierNum;
	}
	public String getTaxonomicClassifierTypeCv() {
		return taxonomicClassifierTypeCv;
	}
	public void setTaxonomicClassifierTypeCv(String taxonomicClassifierTypeCv) {
		this.taxonomicClassifierTypeCv = taxonomicClassifierTypeCv;
	}
	public String getTaxonomicClassifierName() {
		return taxonomicClassifierName;
	}
	public void setTaxonomicClassifierName(String taxonomicClassifierName) {
		this.taxonomicClassifierName = taxonomicClassifierName;
	}
	public String getTaxonomicClassifierCommonName() {
		return taxonomicClassifierCommonName;
	}
	public void setTaxonomicClassifierCommonName(String taxonomicClassifierCommonName) {
		this.taxonomicClassifierCommonName = taxonomicClassifierCommonName;
	}
	public String getTaxonomicClassifierDescription() {
		return taxonomicClassifierDescription;
	}
	public void setTaxonomicClassifierDescription(String taxonomicClassifierDescription) {
		this.taxonomicClassifierDescription = taxonomicClassifierDescription;
	}

	
	
	
	
	
	
	
}
