package org.earthChem.db.postgresql.hbm;

// Generated Jul 30, 2014 4:07:06 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;


/**
 * Variable generated by hbm2java
 */

public class Variable implements java.io.Serializable {

	private Integer variableNum;
	private Integer variableTypeNum;
	private Integer displayOrder;
	private String variableCode;
	private String variableName;
	private String variableTypeCode;
	private String variableDefinition;
	
	public Integer getVariableNum() {
		return variableNum;
	}
	public void setVariableNum(Integer variableNum) {
		this.variableNum = variableNum;
	}
	public Integer getVariableTypeNum() {
		return variableTypeNum;
	}
	public void setVariableTypeNum(Integer variableTypeNum) {
		this.variableTypeNum = variableTypeNum;
	}
	public Integer getDisplayOrder() {
		return displayOrder;
	}
	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}
	public String getVariableCode() {
		return variableCode;
	}
	public void setVariableCode(String variableCode) {
		this.variableCode = variableCode;
	}
	public String getVariableName() {
		return variableName;
	}
	public void setVariableName(String variableName) {
		this.variableName = variableName;
	}
	public String getVariableTypeCode() {
		return variableTypeCode;
	}
	public void setVariableTypeCode(String variableTypeCode) {
		this.variableTypeCode = variableTypeCode;
	}
	public String getVariableDefinition() {
		return variableDefinition;
	}
	public void setVariableDefinition(String variableDefinition) {
		this.variableDefinition = variableDefinition;
	}
	
	
	
	
}
